In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [7]:
### sentences
sentences =[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [8]:
## Define the vocabulary size
voc_size=10000


In [9]:
## One Hot Representation
one_hot_repr = [one_hot(words, voc_size) for words in sentences]
one_hot_repr

[[6646, 4253, 9421, 8864],
 [6646, 4253, 9421, 8977],
 [6646, 3709, 9421, 8444],
 [2633, 2980, 4352, 9230, 898],
 [2633, 2980, 4352, 9230, 8984],
 [9229, 6646, 2002, 9421, 6778],
 [3221, 8401, 4209, 9230]]

In [10]:
## Word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [28]:
sentence_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sentence_length)
print(embedded_docs)

[[   0    0    0    0 7084  326 8751 3800]
 [   0    0    0    0 7084  326 8751 2622]
 [   0    0    0    0 7084 3943 8751 4648]
 [   0    0    0 4568 6468 1185 9515 4405]
 [   0    0    0 4568 6468 1185 9515 8115]
 [   0    0    0 1288 7084 9430 8751 2766]
 [   0    0    0    0 2268  707 2889 9515]]


In [29]:
## Feature representation
dim = 10


In [30]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sentence_length))
model.compile('adam', 'mse')

In [32]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [33]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 156ms/step


array([[[ 2.2622559e-02,  3.9544117e-02,  1.4206294e-02,  4.6401981e-02,
         -3.5512187e-02, -3.6100220e-02,  9.7869523e-03,  2.9979851e-02,
          3.7155319e-02,  1.6194079e-02],
        [ 2.2622559e-02,  3.9544117e-02,  1.4206294e-02,  4.6401981e-02,
         -3.5512187e-02, -3.6100220e-02,  9.7869523e-03,  2.9979851e-02,
          3.7155319e-02,  1.6194079e-02],
        [ 2.2622559e-02,  3.9544117e-02,  1.4206294e-02,  4.6401981e-02,
         -3.5512187e-02, -3.6100220e-02,  9.7869523e-03,  2.9979851e-02,
          3.7155319e-02,  1.6194079e-02],
        [ 2.2622559e-02,  3.9544117e-02,  1.4206294e-02,  4.6401981e-02,
         -3.5512187e-02, -3.6100220e-02,  9.7869523e-03,  2.9979851e-02,
          3.7155319e-02,  1.6194079e-02],
        [ 3.1217448e-03,  4.3454170e-03,  1.7343115e-02,  1.4014337e-02,
         -2.2795750e-02, -1.7484616e-02,  3.3771168e-02,  3.3797387e-02,
          1.3081100e-02,  4.8072960e-02],
        [ 4.7743890e-02,  4.7416892e-02, -2.7576113e-02, -9.

In [34]:
embedded_docs[0]

array([   0,    0,    0,    0, 7084,  326, 8751, 3800])

In [36]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 62ms/step


array([[ 0.02262256,  0.03954412,  0.01420629,  0.04640198, -0.03551219,
        -0.03610022,  0.00978695,  0.02997985,  0.03715532,  0.01619408],
       [ 0.02262256,  0.03954412,  0.01420629,  0.04640198, -0.03551219,
        -0.03610022,  0.00978695,  0.02997985,  0.03715532,  0.01619408],
       [ 0.02262256,  0.03954412,  0.01420629,  0.04640198, -0.03551219,
        -0.03610022,  0.00978695,  0.02997985,  0.03715532,  0.01619408],
       [ 0.02262256,  0.03954412,  0.01420629,  0.04640198, -0.03551219,
        -0.03610022,  0.00978695,  0.02997985,  0.03715532,  0.01619408],
       [ 0.00312174,  0.00434542,  0.01734312,  0.01401434, -0.02279575,
        -0.01748462,  0.03377117,  0.03379739,  0.0130811 ,  0.04807296],
       [ 0.04774389,  0.04741689, -0.02757611, -0.0093023 ,  0.02626925,
         0.02307439,  0.03524033, -0.03756749, -0.03802538, -0.03875099],
       [ 0.01419521,  0.00921044, -0.00420801, -0.03800629,  0.00971768,
         0.03049145, -0.03698565, -0.0019437 